### ISSUE TITLE
"Sign-in" fail when already signed-in

### ISSUE THREAD

**Issue by suzuki** [crowi/crowi#252] opened 2017-08-01 00:35 UTC
## about

1. Already "sign-in" using Google authentication
2. Open login page (`/login`)
3. Click "Google Sign in"
4. "Sign in failure." appeared

<img width="512" alt="2017-08-01 09 32 14" src="https://user-images.githubusercontent.com/10488/28804186-8f82d652-769c-11e7-93d2-420916f8b6c1.png">

## Expected

- move to top page

**Comment by sotarok** [comment] 2018-08-31 01:47
I couldn't reproduce it and  it'll be fixed with `feature/login-flow` (When logged in user access `/login` path then redirect to `/`)

**Closed by sotarok** 2018-08-31 01:47 UTC
Labels: Bug, Can Not Reporo
